events {}

http {
  include       /etc/nginx/mime.types;
  # nginx:alpine mime.types includes application/javascript for .js/.mjs
  default_type  application/octet-stream;
  server_tokens off;

  server {
    listen      80;
    root        /usr/share/nginx/html;
    index       index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
